---
title: "Evaluate Tree Crown Method Based on Segmentation Algorithms"
author: "Ben Weinstein"
date: "4/20/2018"
output: html_document
---

```{r}
library(dplyr)
library(knitr)
library(maptools)
library(TreeSegmentation)
library(ggplot2)
```

# Load in ground-truth
```{r}
shps<-list.files("/Users/ben/Dropbox/Weecology/ECODSEdataset/Task1/ITC/",pattern=".shp",full.names = T)
itcs<-lapply(shps,readShapePoly)

names(itcs)<-sapply(itcs,function(x){
  id<-unique(x$Plot_ID)
  })
print(names(itcs))
plot(itcs[[1]])
```
# Find corresponding tile

```{r,webgl=TRUE}
fname<-get_tile_filname(itcs[[1]])
tile<-readLAS(paste("../data/NEON_D03_OSBS_DP1_402000_3286000_classified_point_cloud.laz"))
summary(tile)
plot(tile)
```

# Silva 2016 Crown Segmentation Model

```{r}
convex_hulls<-silva2016(paste("../data/NEON_D03_OSBS_DP1_402000_3286000_classified_point_cloud.laz"))
plot(convex_hulls)
```

```{r}
clip_ext<-3*extent(itcs[[1]])
clipped_hulls<-raster::crop(convex_hulls,clip_ext)
plot(itcs[[1]],col="red")
plot(clipped_hulls,add=T)
clipped_las<-lasclipRectangle(tile,xleft=clip_ext@xmin,xright=clip_ext@xmax,ytop=clip_ext@ymax,ybottom=clip_ext@ymin)


```{r}
plot(clipped_las)

#add ground truth
trnlim <- range(trn)
trnlen <- trnlim[2] - trnlim[1] + 1
colorlut <- terrain.colors(trnlen,alpha=0) # height color lookup table
col <- colorlut[ trn-trnlim[1]+1 ] # assign colors to heights for each point
open3d()
rgl.surface(x,y,z,color=col)
```

