---
title: "Neon Recall"
author: "Ben Weinstein"
date: "4/20/2018"
output: 
  html_document:
    toc: true
    number_sections: true
editor_options: 
  chunk_output_type: console
---

```{r,warning=F,message=F}
library(tidyverse)
library(xml2)
library(knitr)
library(maptools)
library(rgdal)
library(TreeSegmentation)
library(sp)
library(raster)
library(rgl)
library(lidR)
library(kableExtra)
library(reshape2)

knit_hooks$set(webgl = hook_webgl)
opts_chunk$set(warning=F,message=F)

#set color ramp for treeID
col = pastel.colors(200)

site="TEAK"

#set data paths
path_to_tiles=paste("../data/NeonTreeEvaluation/",site,"/plots/",sep="")
basemap=paste("../data/NeonTreeEvaluation/",site,"/plots/",sep="")

#set cores
cores<-2
#cores<-15
setwd("~/Documents/TreeSegmentation/analysis")
```

# Load in ground-truth
```{r,results='hide'}
dat<-read.csv("../data/Terrestrial/field_data.csv")

sites<-dat %>% filter(siteID==site) %>% droplevels()

#accepted species list
species<-read.csv("../data/NeonTreeEvaluation/AcceptedSpecies.csv")
species<-species %>% filter(siteID %in% site)

#filter data by species
sites <- sites %>% filter(scientificName %in% species$scientificName)

#search for duplicates, ending in a letter
sites<-sites %>% filter(!is.na(as.numeric(str_sub(individualID,-1))))

#Individual trees
trees<-sites  %>% filter(!is.na(UTM_E))

#get tiles to evaluate, match with deep learning 
rgb_tiles<-list.files(paste("/Users/Ben/Documents/DeepLidar/data/",site,"/plots/",sep=""))
plotIDs<-str_match(rgb_tiles,"(\\w+_\\d+).tif")[,2]
plotIDs<-plotIDs[!is.na(plotIDs)]

epsg_df<-data.frame(site=c("SJER","TEAK"),epsg=c("32611","32611"))

#set epsg
epsg_numeric<-epsg_df[epsg_df$site %in% site,"epsg"]

```

```{r}
recalls=list()
  for(x in 1:length(plotIDs)){
    recalls[[x]]<-evaluateNeon(trees=trees,plotID=plotIDs[x],path_to_tiles=path_to_tiles,algorithm = "silva",basemap = basemap,epsg_numeric = epsg_numeric,plot_results=T)
  }

#remove empty rows
print(sum(unlist(recalls))/length(unlist(recalls)))
```

## NEON Precision

#Load XML

```{r}

f<-list.files(paste("../data/NeonTreeEvaluation/",site,"/annotations/",sep=""),pattern=paste(site,"_0",sep=""),full.names = T)

parser<-function(fil){
pg <- read_xml(fil)

# get all the <record>s
recs <- xml_find_all(pg, "//name")
names <- trimws(xml_text(recs))

recs <- xml_find_all(pg, "//xmin")

# extract and clean all the columns
xmin <- trimws(xml_text(recs))

# get all the <record>s
recs <- xml_find_all(pg, "//ymin")

# extract and clean all the columns
ymin <- trimws(xml_text(recs))

# get all the <record>s
recs <- xml_find_all(pg, "//ymax")

# extract and clean all the columns
ymax <- trimws(xml_text(recs))

# get all the <record>s
recs <- xml_find_all(pg, "//xmax")

# extract and clean all the columns
xmax <- trimws(xml_text(recs))

recs <- xml_find_all(pg, "//filename")
filename <- trimws(xml_text(recs))

df<-data.frame(filename,xmin=as.numeric(xmin)*0.1,xmax=as.numeric(xmax)*0.1,ymin=as.numeric(ymin)*0.1,ymax=as.numeric(ymax)*0.1,name=names)
return(df)
}

dat<-bind_rows(lapply(f,parser))
```

Find lidar crops

```{r}

plots<-unique(dat$filename)

computeMAP<-function(plot_name,algorithm="Li",threshold=0.5){
lidar_file<-paste("/Users/ben/Documents/TreeSegmentation/data/NeonTreeEvaluation/",site,"/plots/",str_match(plot_name,"(\\w+).tif")[,2],".laz",sep="")

#check if exists
if(!file.exists(lidar_file)){
  return(NULL)
}

#Tree predictions
if(algorithm=="Dalponte"){
  results<-run_dalponte2016(path=lidar_file,epsg_numeric=epsg_numeric)
}

if(algorithm=="Li"){
    results<-run_li2012(path=lidar_file,epsg_numeric=epsg_numeric)
}

if(algorithm=="Silva"){
    results<-run_silva2016(path=lidar_file,epsg_numeric=epsg_numeric)

}
#hand annotations as spdf
plot_data<-dat %>% filter(filename==plot_name)

#Project 
projection_extent<-extent(readLAS(lidar_file))

ground_truth<-list()
for(x in 1:nrow(plot_data)){
  
  e<-extent( projection_extent@xmin + plot_data$xmin[x],
             projection_extent@xmin + plot_data$xmax[x], 
            (projection_extent@ymax - plot_data$ymax[x]),
             (projection_extent@ymax - plot_data$ymax[x]) + (plot_data$ymax[x] - plot_data$ymin[x]) )
  ground_truth[[x]]<-as(e, 'SpatialPolygons')
  ground_truth[[x]]@polygons[[1]]@ID<-as.character(x)
}

ground_truth <- as(SpatialPolygons(lapply(ground_truth,
                                          function(x) slot(x, "polygons")[[1]])),"SpatialPolygonsDataFrame")

ground_truth@data$crown_id=1:nrow(ground_truth)

proj4string(ground_truth)<-projection(results$tile)

#predictions
predictions<-tree_hulls(results$tile)

#match names
predictions$ID<-1:nrow(predictions)

r<-stack(paste("../data/NeonTreeEvaluation/",site,"/plots/",plot_name,sep=""))
tiff(paste("plots/",algorithm,"/",plot_name,sep=""))
plotRGB(r)
#plot(ground_truth,add=T,border="green",bg="transparent")
plot(predictions,add=T,border="orange",bg="transparent",lwd=4)
dev.off()

#If there is only one prediction, skip assignment
if(nrow(predictions) > nrow(ground_truth)){
  assignment<-assign_trees(ground_truth=ground_truth,prediction=predictions)

  statdf<-calc_jaccard(assignment=assignment,ground_truth = ground_truth,prediction=predictions)
} else{
  
  #Find max overlap
  po<-polygon_overlap_all(ground_truth,predictions)
  statdf<-po %>% group_by(prediction_id) %>% filter(area==max(area)) %>% group_by(crown_id,prediction_id) %>% do(data.frame(IoU=IoU(ground_truth[.$crown_id,],predictions[.$prediction_id,])))
}

results<-data.frame(plot_name, true_positives = statdf$IoU > threshold, false_positives = statdf$IoU < threshold)
return(results)
}
```

For each algorithm

```{r}
run_all<-function(plots,dat){
  df<-list()

  algorithms<-c("Silva")

  for(x in 1:length(algorithms)){
    maP_list<-lapply(plots,computeMAP,algorithm=algorithms[x],threshold=0.5)
    maPdf<-bind_rows(maP_list)
    recall <- sum(maPdf$true_positives,na.rm=T)/nrow(dat)
    precision <- sum(maPdf$true_positives,na.rm=T)/nrow(maPdf)
    df[[x]]<-data.frame(Algorithm=algorithms[x],recall=recall,precision=precision)
  }
  return(melt(df))
}

result_table<-run_all(plots,dat)

result_table %>% tidyr::spread(variable,value) %>% arrange(recall)
```
