library(NeonTreeEvaluation)
library(dplyr)
library(raster)
library(sf)
dat<-xml_parse("/Users/ben/Dropbox/Weecology/Benchmark/NEON_field_polygons/crops/2.xml")
r<-stack("/Users/ben/Dropbox/Weecology/Benchmark/NEON_field_polygons/crops/2.tif")
s<-boxes_to_spatial_polygons(dat,r)
write_sf(st_as_sf(s), "/Users/ben/Dropbox/Weecology/Benchmark/NEON_field_polygons/crops/2.shp")
